controllers-films-users
ds111166/java-filmorate pull request #8
Opened 2023-08-08 05:36 UTC by ds111166

Класс пользователь
Класс фильм
Rest контроллер пользователей
эндпоинты для UserController: создание пользователя; обновление пользователя; получение списка всех пользователей
Rest контроллер фильмов
эндпоинты для FilmController: добавление фильма; обновление фильма; получение всех фильмов.
Логирование для операций, которые изменяют сущности — добавляют и обновляют их. Также логирование причины ошибок
Валидация сущностей пользователей и фильмов на основе spring-boot-starter-validation
Тестовое покрытие контроллеров

2023-08-08 13:55 UTC, YazykovMikhail requested changes

2023-08-08 13:55 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        newFilm.setId(generatorId);
```
newFilm.setId(generatorId);
        films.put(generatorId++, newFilm);
```
выглядит не очень согласен?
```
final long id = ++generatorId;
 newFilm.setId(id); 
  films.put(newFilm.getId(), newFilm);
```

поправь везде

2023-08-08 13:55 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private int generatorId = 1;
для id лучше использовать long
и начинать с 0

2023-08-08 13:55 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotEmpty(message = "название не может быть пустым")
для строк лучше использовать NotBlank
посмотри какая между ними разница

2023-08-08 13:55 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public Collection<User> getUsers() {
Сильно абстрактно, чаще всего использует public List<User> getUsers() {

2023-08-08 13:55 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public static final int FILM_DESCRIPTION_MAX_LENGTH = 200;
лишнее, получается к этому полю в модели можно обратитсья. А его нет. 
просто пиши 200 в аннотации и так понятно что это, потому что там у поля есть имя

2023-08-09 07:32 UTC, ds111166 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        newFilm.setId(generatorId);
поправил

2023-08-09 07:32 UTC, ds111166 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private int generatorId = 1;
поправил

2023-08-09 07:32 UTC, ds111166 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotEmpty(message = "название не может быть пустым")
поправил

2023-08-09 07:32 UTC, ds111166 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public Collection<User> getUsers() {
поправил

2023-08-09 07:33 UTC, ds111166 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public static final int FILM_DESCRIPTION_MAX_LENGTH = 200;
поправил

2023-08-09 14:05 UTC, YazykovMikhail approved these changes

2023-08-09 17:56 UTC, merged